package com.dezxxx.individuals.gateway.keycloak;

import com.dezxxx.individuals.api.model.TokenResponse;
import com.dezxxx.individuals.config.KeycloakProperties;
import com.dezxxx.individuals.error.ApiException;
import com.dezxxx.individuals.error.ErrorCode;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.http.HttpStatusCode;
import org.springframework.stereotype.Component;
import org.springframework.util.LinkedMultiValueMap;
import org.springframework.util.MultiValueMap;
import org.springframework.web.reactive.function.BodyInserters;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Mono;

/**
 * The only class that knows how Keycloak issues tokens.
 *
 * <p>All three operations hit the same endpoint and differ only in
 * {@code grant_type}: a user logging in, a user refreshing, and this service
 * authenticating as itself to reach the Admin API.
 *
 * <p>The body is a form, not JSON - the OIDC token endpoint accepts nothing
 * else. Above this class no one knows that.
 *
 * <p>Every method answers with {@code TokenResponse}, the type our own contract
 * defines. Keycloak's shape stops here.
 */
@Slf4j
@Component
public class KeycloakOidcGateway {

    private static final String GRANT_TYPE = "grant_type";

    private static final String CLIENT_ID = "client_id";

    private static final String CLIENT_SECRET = "client_secret";

    private final WebClient keycloakWebClient;

    private final KeycloakProperties properties;

    /**
     * Two WebClient beans exist, so the one meant for Keycloak is named
     * explicitly. Written out rather than generated by Lombok because
     * {@code @Qualifier} is not copied onto a generated constructor.
     */
    public KeycloakOidcGateway(@Qualifier("keycloakWebClient") WebClient keycloakWebClient,
                               KeycloakProperties properties) {
        this.keycloakWebClient = keycloakWebClient;
        this.properties = properties;
    }

    /** Exchanges an email and a password for a fresh pair of tokens. */
    public Mono<TokenResponse> login(String email, String password) {
        MultiValueMap<String, String> form = clientForm("password");
        form.add("username", email);
        form.add("password", password);
        return requestToken(form).map(KeycloakOidcGateway::toTokenResponse);
    }

    /**
     * Exchanges a refresh token for a new pair.
     *
     * <p>Keycloak rotates the refresh token, so the answer carries a new one
     * and the old one stops working. The caller must store what comes back.
     */
    public Mono<TokenResponse> refresh(String refreshToken) {
        MultiValueMap<String, String> form = clientForm("refresh_token");
        form.add("refresh_token", refreshToken);
        return requestToken(form).map(KeycloakOidcGateway::toTokenResponse);
    }

    /**
     * Authenticates this service as itself and returns the raw access token.
     *
     * <p>Needed by the Admin API calls, which act on behalf of the service
     * account rather than of a user. Only the token string is returned - the
     * rest of the answer is of no use to the caller.
     *
     * <p>No caching yet: every admin call fetches a token of its own. That is
     * one extra round trip to a Keycloak that sits in the same compose network,
     * and it keeps the first version free of expiry bookkeeping.
     */
    public Mono<String> serviceAccountToken() {
        return requestToken(clientForm("client_credentials"))
                .map(KeycloakTokenResponse::accessToken);
    }

    private Mono<KeycloakTokenResponse> requestToken(MultiValueMap<String, String> form) {
        return keycloakWebClient.post()
                .uri(properties.tokenUri())
                .body(BodyInserters.fromFormData(form))
                .retrieve()
                .onStatus(HttpStatusCode::isError, KeycloakErrorTranslator::translate)
                .bodyToMono(KeycloakTokenResponse.class)
                // Connection refused, DNS failure, timeout: Keycloak never
                // answered, so this is a dependency problem, not a caller
                // mistake. ApiException is already ours and passes through.
                .onErrorMap(ex -> !(ex instanceof ApiException), ex -> {
                    log.error("Keycloak is unreachable at {}", properties.baseUrl(), ex);
                    return new ApiException(ErrorCode.DEPENDENCY_UNAVAILABLE);
                });
    }

    /** The three fields every grant needs: which grant, and who is asking. */
    private MultiValueMap<String, String> clientForm(String grantType) {
        MultiValueMap<String, String> form = new LinkedMultiValueMap<>();
        form.add(GRANT_TYPE, grantType);
        form.add(CLIENT_ID, properties.clientId());
        form.add(CLIENT_SECRET, properties.clientSecret());
        return form;
    }

    /**
     * Keycloak's shape to ours. {@code userUid} stays empty on purpose: it is
     * not part of a token answer, and the service above fills it from the
     * token's claim or from the registration it just performed.
     */
    private static TokenResponse toTokenResponse(KeycloakTokenResponse source) {
        return new TokenResponse()
                .accessToken(source.accessToken())
                .refreshToken(source.refreshToken())
                .expiresIn(source.expiresIn())
                .tokenType(source.tokenType());
    }
}
