-- Reference data: ISO 3166-1 countries and territories.
--
-- Names are the ISO 3166-1 English short names; alpha2 and alpha3 are the
-- load-bearing columns - they are what other systems address a country by,
-- and both carry a UNIQUE constraint.
--
-- Every row starts ACTIVE. INACTIVE is for territories the platform stops
-- serving; it is a business decision, never a property of the standard, so it
-- is changed by data, not by a migration.
--
-- ON CONFLICT keeps the statement replayable in a scratch database that was
-- partially seeded by hand. Flyway still applies this migration exactly once.

INSERT INTO person.countries (name, alpha2, alpha3, status) VALUES
    ('Afghanistan', 'AF', 'AFG', 'ACTIVE'),
    ('Åland Islands', 'AX', 'ALA', 'ACTIVE'),
    ('Albania', 'AL', 'ALB', 'ACTIVE'),
    ('Algeria', 'DZ', 'DZA', 'ACTIVE'),
    ('American Samoa', 'AS', 'ASM', 'ACTIVE'),
    ('Andorra', 'AD', 'AND', 'ACTIVE'),
    ('Angola', 'AO', 'AGO', 'ACTIVE'),
    ('Anguilla', 'AI', 'AIA', 'ACTIVE'),
    ('Antarctica', 'AQ', 'ATA', 'ACTIVE'),
    ('Antigua and Barbuda', 'AG', 'ATG', 'ACTIVE'),
    ('Argentina', 'AR', 'ARG', 'ACTIVE'),
    ('Armenia', 'AM', 'ARM', 'ACTIVE'),
    ('Aruba', 'AW', 'ABW', 'ACTIVE'),
    ('Australia', 'AU', 'AUS', 'ACTIVE'),
    ('Austria', 'AT', 'AUT', 'ACTIVE'),
    ('Azerbaijan', 'AZ', 'AZE', 'ACTIVE'),
    ('Bahamas', 'BS', 'BHS', 'ACTIVE'),
    ('Bahrain', 'BH', 'BHR', 'ACTIVE'),
    ('Bangladesh', 'BD', 'BGD', 'ACTIVE'),
    ('Barbados', 'BB', 'BRB', 'ACTIVE'),
    ('Belarus', 'BY', 'BLR', 'ACTIVE'),
    ('Belgium', 'BE', 'BEL', 'ACTIVE'),
    ('Belize', 'BZ', 'BLZ', 'ACTIVE'),
    ('Benin', 'BJ', 'BEN', 'ACTIVE'),
    ('Bermuda', 'BM', 'BMU', 'ACTIVE'),
    ('Bhutan', 'BT', 'BTN', 'ACTIVE'),
    ('Bolivia', 'BO', 'BOL', 'ACTIVE'),
    ('Bonaire, Sint Eustatius and Saba', 'BQ', 'BES', 'ACTIVE'),
    ('Bosnia and Herzegovina', 'BA', 'BIH', 'ACTIVE'),
    ('Botswana', 'BW', 'BWA', 'ACTIVE'),
    ('Bouvet Island', 'BV', 'BVT', 'ACTIVE'),
    ('Brazil', 'BR', 'BRA', 'ACTIVE'),
    ('British Indian Ocean Territory', 'IO', 'IOT', 'ACTIVE'),
    ('Brunei Darussalam', 'BN', 'BRN', 'ACTIVE'),
    ('Bulgaria', 'BG', 'BGR', 'ACTIVE'),
    ('Burkina Faso', 'BF', 'BFA', 'ACTIVE'),
    ('Burundi', 'BI', 'BDI', 'ACTIVE'),
    ('Cabo Verde', 'CV', 'CPV', 'ACTIVE'),
    ('Cambodia', 'KH', 'KHM', 'ACTIVE'),
    ('Cameroon', 'CM', 'CMR', 'ACTIVE'),
    ('Canada', 'CA', 'CAN', 'ACTIVE'),
    ('Cayman Islands', 'KY', 'CYM', 'ACTIVE'),
    ('Central African Republic', 'CF', 'CAF', 'ACTIVE'),
    ('Chad', 'TD', 'TCD', 'ACTIVE'),
    ('Chile', 'CL', 'CHL', 'ACTIVE'),
    ('China', 'CN', 'CHN', 'ACTIVE'),
    ('Christmas Island', 'CX', 'CXR', 'ACTIVE'),
    ('Cocos (Keeling) Islands', 'CC', 'CCK', 'ACTIVE'),
    ('Colombia', 'CO', 'COL', 'ACTIVE'),
    ('Comoros', 'KM', 'COM', 'ACTIVE'),
    ('Congo', 'CG', 'COG', 'ACTIVE'),
    ('Congo, Democratic Republic of the', 'CD', 'COD', 'ACTIVE'),
    ('Cook Islands', 'CK', 'COK', 'ACTIVE'),
    ('Costa Rica', 'CR', 'CRI', 'ACTIVE'),
    ('Côte d''Ivoire', 'CI', 'CIV', 'ACTIVE'),
    ('Croatia', 'HR', 'HRV', 'ACTIVE'),
    ('Cuba', 'CU', 'CUB', 'ACTIVE'),
    ('Curaçao', 'CW', 'CUW', 'ACTIVE'),
    ('Cyprus', 'CY', 'CYP', 'ACTIVE'),
    ('Czechia', 'CZ', 'CZE', 'ACTIVE'),
    ('Denmark', 'DK', 'DNK', 'ACTIVE'),
    ('Djibouti', 'DJ', 'DJI', 'ACTIVE'),
    ('Dominica', 'DM', 'DMA', 'ACTIVE'),
    ('Dominican Republic', 'DO', 'DOM', 'ACTIVE'),
    ('Ecuador', 'EC', 'ECU', 'ACTIVE'),
    ('Egypt', 'EG', 'EGY', 'ACTIVE'),
    ('El Salvador', 'SV', 'SLV', 'ACTIVE'),
    ('Equatorial Guinea', 'GQ', 'GNQ', 'ACTIVE'),
    ('Eritrea', 'ER', 'ERI', 'ACTIVE'),
    ('Estonia', 'EE', 'EST', 'ACTIVE'),
    ('Eswatini', 'SZ', 'SWZ', 'ACTIVE'),
    ('Ethiopia', 'ET', 'ETH', 'ACTIVE'),
    ('Falkland Islands', 'FK', 'FLK', 'ACTIVE'),
    ('Faroe Islands', 'FO', 'FRO', 'ACTIVE'),
    ('Fiji', 'FJ', 'FJI', 'ACTIVE'),
    ('Finland', 'FI', 'FIN', 'ACTIVE'),
    ('France', 'FR', 'FRA', 'ACTIVE'),
    ('French Guiana', 'GF', 'GUF', 'ACTIVE'),
    ('French Polynesia', 'PF', 'PYF', 'ACTIVE'),
    ('French Southern Territories', 'TF', 'ATF', 'ACTIVE'),
    ('Gabon', 'GA', 'GAB', 'ACTIVE'),
    ('Gambia', 'GM', 'GMB', 'ACTIVE'),
    ('Georgia', 'GE', 'GEO', 'ACTIVE'),
    ('Germany', 'DE', 'DEU', 'ACTIVE'),
    ('Ghana', 'GH', 'GHA', 'ACTIVE'),
    ('Gibraltar', 'GI', 'GIB', 'ACTIVE'),
    ('Greece', 'GR', 'GRC', 'ACTIVE'),
    ('Greenland', 'GL', 'GRL', 'ACTIVE'),
    ('Grenada', 'GD', 'GRD', 'ACTIVE'),
    ('Guadeloupe', 'GP', 'GLP', 'ACTIVE'),
    ('Guam', 'GU', 'GUM', 'ACTIVE'),
    ('Guatemala', 'GT', 'GTM', 'ACTIVE'),
    ('Guernsey', 'GG', 'GGY', 'ACTIVE'),
    ('Guinea', 'GN', 'GIN', 'ACTIVE'),
    ('Guinea-Bissau', 'GW', 'GNB', 'ACTIVE'),
    ('Guyana', 'GY', 'GUY', 'ACTIVE'),
    ('Haiti', 'HT', 'HTI', 'ACTIVE'),
    ('Heard Island and McDonald Islands', 'HM', 'HMD', 'ACTIVE'),
    ('Holy See', 'VA', 'VAT', 'ACTIVE'),
    ('Honduras', 'HN', 'HND', 'ACTIVE'),
    ('Hong Kong', 'HK', 'HKG', 'ACTIVE'),
    ('Hungary', 'HU', 'HUN', 'ACTIVE'),
    ('Iceland', 'IS', 'ISL', 'ACTIVE'),
    ('India', 'IN', 'IND', 'ACTIVE'),
    ('Indonesia', 'ID', 'IDN', 'ACTIVE'),
    ('Iran', 'IR', 'IRN', 'ACTIVE'),
    ('Iraq', 'IQ', 'IRQ', 'ACTIVE'),
    ('Ireland', 'IE', 'IRL', 'ACTIVE'),
    ('Isle of Man', 'IM', 'IMN', 'ACTIVE'),
    ('Israel', 'IL', 'ISR', 'ACTIVE'),
    ('Italy', 'IT', 'ITA', 'ACTIVE'),
    ('Jamaica', 'JM', 'JAM', 'ACTIVE'),
    ('Japan', 'JP', 'JPN', 'ACTIVE'),
    ('Jersey', 'JE', 'JEY', 'ACTIVE'),
    ('Jordan', 'JO', 'JOR', 'ACTIVE'),
    ('Kazakhstan', 'KZ', 'KAZ', 'ACTIVE'),
    ('Kenya', 'KE', 'KEN', 'ACTIVE'),
    ('Kiribati', 'KI', 'KIR', 'ACTIVE'),
    ('Korea, Democratic People''s Republic of', 'KP', 'PRK', 'ACTIVE'),
    ('Korea, Republic of', 'KR', 'KOR', 'ACTIVE'),
    ('Kuwait', 'KW', 'KWT', 'ACTIVE'),
    ('Kyrgyzstan', 'KG', 'KGZ', 'ACTIVE'),
    ('Lao People''s Democratic Republic', 'LA', 'LAO', 'ACTIVE'),
    ('Latvia', 'LV', 'LVA', 'ACTIVE'),
    ('Lebanon', 'LB', 'LBN', 'ACTIVE'),
    ('Lesotho', 'LS', 'LSO', 'ACTIVE'),
    ('Liberia', 'LR', 'LBR', 'ACTIVE'),
    ('Libya', 'LY', 'LBY', 'ACTIVE'),
    ('Liechtenstein', 'LI', 'LIE', 'ACTIVE'),
    ('Lithuania', 'LT', 'LTU', 'ACTIVE'),
    ('Luxembourg', 'LU', 'LUX', 'ACTIVE'),
    ('Macao', 'MO', 'MAC', 'ACTIVE'),
    ('Madagascar', 'MG', 'MDG', 'ACTIVE'),
    ('Malawi', 'MW', 'MWI', 'ACTIVE'),
    ('Malaysia', 'MY', 'MYS', 'ACTIVE'),
    ('Maldives', 'MV', 'MDV', 'ACTIVE'),
    ('Mali', 'ML', 'MLI', 'ACTIVE'),
    ('Malta', 'MT', 'MLT', 'ACTIVE'),
    ('Marshall Islands', 'MH', 'MHL', 'ACTIVE'),
    ('Martinique', 'MQ', 'MTQ', 'ACTIVE'),
    ('Mauritania', 'MR', 'MRT', 'ACTIVE'),
    ('Mauritius', 'MU', 'MUS', 'ACTIVE'),
    ('Mayotte', 'YT', 'MYT', 'ACTIVE'),
    ('Mexico', 'MX', 'MEX', 'ACTIVE'),
    ('Micronesia', 'FM', 'FSM', 'ACTIVE'),
    ('Moldova', 'MD', 'MDA', 'ACTIVE'),
    ('Monaco', 'MC', 'MCO', 'ACTIVE'),
    ('Mongolia', 'MN', 'MNG', 'ACTIVE'),
    ('Montenegro', 'ME', 'MNE', 'ACTIVE'),
    ('Montserrat', 'MS', 'MSR', 'ACTIVE'),
    ('Morocco', 'MA', 'MAR', 'ACTIVE'),
    ('Mozambique', 'MZ', 'MOZ', 'ACTIVE'),
    ('Myanmar', 'MM', 'MMR', 'ACTIVE'),
    ('Namibia', 'NA', 'NAM', 'ACTIVE'),
    ('Nauru', 'NR', 'NRU', 'ACTIVE'),
    ('Nepal', 'NP', 'NPL', 'ACTIVE'),
    ('Netherlands', 'NL', 'NLD', 'ACTIVE'),
    ('New Caledonia', 'NC', 'NCL', 'ACTIVE'),
    ('New Zealand', 'NZ', 'NZL', 'ACTIVE'),
    ('Nicaragua', 'NI', 'NIC', 'ACTIVE'),
    ('Niger', 'NE', 'NER', 'ACTIVE'),
    ('Nigeria', 'NG', 'NGA', 'ACTIVE'),
    ('Niue', 'NU', 'NIU', 'ACTIVE'),
    ('Norfolk Island', 'NF', 'NFK', 'ACTIVE'),
    ('North Macedonia', 'MK', 'MKD', 'ACTIVE'),
    ('Northern Mariana Islands', 'MP', 'MNP', 'ACTIVE'),
    ('Norway', 'NO', 'NOR', 'ACTIVE'),
    ('Oman', 'OM', 'OMN', 'ACTIVE'),
    ('Pakistan', 'PK', 'PAK', 'ACTIVE'),
    ('Palau', 'PW', 'PLW', 'ACTIVE'),
    ('Palestine, State of', 'PS', 'PSE', 'ACTIVE'),
    ('Panama', 'PA', 'PAN', 'ACTIVE'),
    ('Papua New Guinea', 'PG', 'PNG', 'ACTIVE'),
    ('Paraguay', 'PY', 'PRY', 'ACTIVE'),
    ('Peru', 'PE', 'PER', 'ACTIVE'),
    ('Philippines', 'PH', 'PHL', 'ACTIVE'),
    ('Pitcairn', 'PN', 'PCN', 'ACTIVE'),
    ('Poland', 'PL', 'POL', 'ACTIVE'),
    ('Portugal', 'PT', 'PRT', 'ACTIVE'),
    ('Puerto Rico', 'PR', 'PRI', 'ACTIVE'),
    ('Qatar', 'QA', 'QAT', 'ACTIVE'),
    ('Réunion', 'RE', 'REU', 'ACTIVE'),
    ('Romania', 'RO', 'ROU', 'ACTIVE'),
    ('Russian Federation', 'RU', 'RUS', 'ACTIVE'),
    ('Rwanda', 'RW', 'RWA', 'ACTIVE'),
    ('Saint Barthélemy', 'BL', 'BLM', 'ACTIVE'),
    ('Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', 'ACTIVE'),
    ('Saint Kitts and Nevis', 'KN', 'KNA', 'ACTIVE'),
    ('Saint Lucia', 'LC', 'LCA', 'ACTIVE'),
    ('Saint Martin (French part)', 'MF', 'MAF', 'ACTIVE'),
    ('Saint Pierre and Miquelon', 'PM', 'SPM', 'ACTIVE'),
    ('Saint Vincent and the Grenadines', 'VC', 'VCT', 'ACTIVE'),
    ('Samoa', 'WS', 'WSM', 'ACTIVE'),
    ('San Marino', 'SM', 'SMR', 'ACTIVE'),
    ('Sao Tome and Principe', 'ST', 'STP', 'ACTIVE'),
    ('Saudi Arabia', 'SA', 'SAU', 'ACTIVE'),
    ('Senegal', 'SN', 'SEN', 'ACTIVE'),
    ('Serbia', 'RS', 'SRB', 'ACTIVE'),
    ('Seychelles', 'SC', 'SYC', 'ACTIVE'),
    ('Sierra Leone', 'SL', 'SLE', 'ACTIVE'),
    ('Singapore', 'SG', 'SGP', 'ACTIVE'),
    ('Sint Maarten (Dutch part)', 'SX', 'SXM', 'ACTIVE'),
    ('Slovakia', 'SK', 'SVK', 'ACTIVE'),
    ('Slovenia', 'SI', 'SVN', 'ACTIVE'),
    ('Solomon Islands', 'SB', 'SLB', 'ACTIVE'),
    ('Somalia', 'SO', 'SOM', 'ACTIVE'),
    ('South Africa', 'ZA', 'ZAF', 'ACTIVE'),
    ('South Georgia and the South Sandwich Islands', 'GS', 'SGS', 'ACTIVE'),
    ('South Sudan', 'SS', 'SSD', 'ACTIVE'),
    ('Spain', 'ES', 'ESP', 'ACTIVE'),
    ('Sri Lanka', 'LK', 'LKA', 'ACTIVE'),
    ('Sudan', 'SD', 'SDN', 'ACTIVE'),
    ('Suriname', 'SR', 'SUR', 'ACTIVE'),
    ('Svalbard and Jan Mayen', 'SJ', 'SJM', 'ACTIVE'),
    ('Sweden', 'SE', 'SWE', 'ACTIVE'),
    ('Switzerland', 'CH', 'CHE', 'ACTIVE'),
    ('Syrian Arab Republic', 'SY', 'SYR', 'ACTIVE'),
    ('Taiwan', 'TW', 'TWN', 'ACTIVE'),
    ('Tajikistan', 'TJ', 'TJK', 'ACTIVE'),
    ('Tanzania', 'TZ', 'TZA', 'ACTIVE'),
    ('Thailand', 'TH', 'THA', 'ACTIVE'),
    ('Timor-Leste', 'TL', 'TLS', 'ACTIVE'),
    ('Togo', 'TG', 'TGO', 'ACTIVE'),
    ('Tokelau', 'TK', 'TKL', 'ACTIVE'),
    ('Tonga', 'TO', 'TON', 'ACTIVE'),
    ('Trinidad and Tobago', 'TT', 'TTO', 'ACTIVE'),
    ('Tunisia', 'TN', 'TUN', 'ACTIVE'),
    ('Türkiye', 'TR', 'TUR', 'ACTIVE'),
    ('Turkmenistan', 'TM', 'TKM', 'ACTIVE'),
    ('Turks and Caicos Islands', 'TC', 'TCA', 'ACTIVE'),
    ('Tuvalu', 'TV', 'TUV', 'ACTIVE'),
    ('Uganda', 'UG', 'UGA', 'ACTIVE'),
    ('Ukraine', 'UA', 'UKR', 'ACTIVE'),
    ('United Arab Emirates', 'AE', 'ARE', 'ACTIVE'),
    ('United Kingdom', 'GB', 'GBR', 'ACTIVE'),
    ('United States', 'US', 'USA', 'ACTIVE'),
    ('United States Minor Outlying Islands', 'UM', 'UMI', 'ACTIVE'),
    ('Uruguay', 'UY', 'URY', 'ACTIVE'),
    ('Uzbekistan', 'UZ', 'UZB', 'ACTIVE'),
    ('Vanuatu', 'VU', 'VUT', 'ACTIVE'),
    ('Venezuela', 'VE', 'VEN', 'ACTIVE'),
    ('Viet Nam', 'VN', 'VNM', 'ACTIVE'),
    ('Virgin Islands (British)', 'VG', 'VGB', 'ACTIVE'),
    ('Virgin Islands (U.S.)', 'VI', 'VIR', 'ACTIVE'),
    ('Wallis and Futuna', 'WF', 'WLF', 'ACTIVE'),
    ('Western Sahara', 'EH', 'ESH', 'ACTIVE'),
    ('Yemen', 'YE', 'YEM', 'ACTIVE'),
    ('Zambia', 'ZM', 'ZMB', 'ACTIVE'),
    ('Zimbabwe', 'ZW', 'ZWE', 'ACTIVE')
ON CONFLICT (alpha2) DO NOTHING;
